[versions]
# libraries
junit = "4.13.2"
opentest4j = "1.3.0"
kotlinx-serialization-json = "1.9.0"
yamlkt = "0.13.0"
ktoml = "0.7.1"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.3.0"
kover = "0.9.4"
qodana = "2025.2.4"
serialization = "2.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
yamlkt = { group = "net.mamoe.yamlkt", name = "yamlkt-jvm", version.ref = "yamlkt" }
ktoml-core = { group = "com.akuleshov7", name = "ktoml-core", version.ref = "ktoml" }
ktoml-file = { group = "com.akuleshov7", name = "ktoml-file", version.ref = "ktoml" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
